CREATE TABLE `student_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`role` enum('student','parent') NOT NULL,
	`studentName` varchar(128),
	`grade` varchar(64) NOT NULL,
	`board` enum('CBSE','ICSE','State','IB','IGCSE','Other') NOT NULL,
	`subjects` varchar(512) NOT NULL,
	`mode` enum('home_tuition','online','both') NOT NULL,
	`demoTime` varchar(128),
	`regularTime` varchar(128),
	`daysPerWeek` varchar(128),
	`sessionsPerWeek` varchar(32),
	`sessionDuration` varchar(64),
	`budget` varchar(64),
	`specialRequirements` text,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`fullAddress` text,
	`area` varchar(128),
	`isActive` enum('yes','no') NOT NULL DEFAULT 'yes',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `student_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `tutor_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tutorTableId` int,
	`name` varchar(128) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`photo` varchar(512),
	`qualification` varchar(256) NOT NULL,
	`subjects` varchar(512) NOT NULL,
	`experience` varchar(64) NOT NULL,
	`boards` varchar(256) NOT NULL DEFAULT 'CBSE, ICSE',
	`languages` varchar(256) NOT NULL DEFAULT 'English, Kannada',
	`mode` enum('home_tuition','online','both') NOT NULL DEFAULT 'both',
	`bio` text,
	`demoTime` varchar(128),
	`regularTime` varchar(128),
	`sessionDuration` varchar(64),
	`daysPerWeek` varchar(128),
	`firstMonthFee` varchar(32),
	`nextMonthFee` varchar(32),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`fullAddress` text,
	`area` varchar(128),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tutor_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `tutor_profiles_userId_unique` UNIQUE(`userId`)
);
